#!/bin/sh
alias j='z'
alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Easier navigation: .., ..., ~ and -
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# ls
alias la='ls -A'
alias l='ls -CF'
alias ll='ls -halF'
alias ls='ls --classify --tabsize=0 --group-directories-first --literal --color=auto --show-control-chars --human-readable'

# confirm before overwriting something
# mv, rm, cp
alias cp="cp -i -r -v"
alias mv="mv -i -v"
alias rm="rm -i -v"

# Edit config files in nvim
# $EDITOR=nvim 
alias v='nvim'
alias vim='nvim'
alias vrc="$EDITOR  /home/morp/.config/nvim/init.vim"
alias sv="sudo $EDITOR"
alias ec="$EDITOR $HOME/.zshrc"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Networking. IP address, dig, DNS
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
# alias wget="curl -O"
# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

case "$(uname -r)" in

    #'Mac OS X'
    Darwin)
    alias ls='ls -G'
    ;;

    #'Arch Linux'
    arch*)
    alias ls='ls --color=auto'
    # get fastest mirrors
    alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
    alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
    alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
    alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
    ;;

    #'Linux'
    Linux)
    alias ls='ls --color=auto'
    ;;

    #'Cygwin'
    CYGWIN*|MINGW32*|MSYS*|MINGW*)
    # echo 'MS Windows'
    ;;

    #'WSL2'
    WSL*|micorsoft*)
    # WSL Alias
    alias explorer='/mnt/c/Windows/explorer.exe'
    alias pdf="/mnt/c/Progam\ Files\ (x86)/Adobe/Acrobat\ Reader\ DC/Readerr/AcroRd32.exe"
    alias pdfviewer="/mnt/c/Users/NAmoa/AppData/Local/SumatraPDF/SumatraPDF.exe"
    alias brave="/mnt/c/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"
    ;;

    #'Other OS' 
    *)
    ;;
esac

#{{{ colorize stuff, utility commands
#{{{ Detect which `ls` flavor is in use
if ls --color >/dev/null 2>&1; then # GNU `ls`
    colorflag="--color=auto"
else # OS X `ls`
    colorflag="-G"
fi
if [[ "$INSIDE_EMACS" ]]; then
    colorflag=""
fi
#}}}
#{{{ pretty ls
# List all files colorized in long format
alias l="ls -Fl ${colorflag}"
alias ls-a="ls -Fa ${colorflag}"
# List all files colorized in long format, including dot files
alias la="ls -Fla ${colorflag}"
alias ll="ls -Fl ${colorflag}"
# List only directories
alias lsd='ls -Fl ${colorflag} | grep "^d"'
# Always use color output for `ls`
alias ls="command ls -F ${colorflag}"
#}}}
#}}}
#{{{ volume control
alias maxvol="amixer -c 0 -- set Master 100%"
alias headphones="amixer -c 0 -- set Master 45%"
alias mute="amixer -c 0 -- set Master mute"
alias unmute="amixer -c 0 -- set Master on"
#}}}

# Set personal aliases
alias dotfiles="cd $HOME/dotfiles"
alias zshrc="nvim ~/.zshrc"
alias bashrc="nvim ~/.bashrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias nvimrc='nvim /home/morp/.config/nvim/init.vim'
alias rd="rmdir"
alias update="sudo apt update && sudo apt upgrade -y"
alias ip='ip -color=auto'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias pip='pip3'
alias python='python3'
alias weather='curl wttr.in'
alias lcthw="cd ~/Programs/CPrograms/LCTHW/"
alias bat="batcat"
alias lsb="lsb_release -a"
alias nvdir="cd $HOME/.config/nvim"
alias lua="lua5.2"

