#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export MANWIDTH=999
export PATH="$HOME/.local/bin":$PATH
# HISTFILE="$XDG_DATA_HOME/zsh/history"
# HISTSIZE=1000000
# SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
# export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

export STARSHIP_CONFIG=~/.config/starship/config.toml
eval "$(starship init zsh)"
