#!/bin/zsh
# Normalize `open` across Linux, macOS, and Windows.
# This is needed to make the `o` function (see below) cross-platform.

# if [ ! $(uname -s) = 'Darwin' ]; then
#     if grep -q Microsoft /proc/version; then
#         # Ubuntu on Windows using the Linux subsystem
#         alias open='explorer.exe';
#     else
#         alias open='xdg-open';
#     fi
# fi

# case "$OSTYPE" in
#   cygwin*)
#     alias open="cmd /c start"
#     ;;
#   linux*)
#     alias start="xdg-open"
#     alias open="xdg-open"
#     ;;
#   darwin*)
#     alias start="open"
#     ;;
# esac

case "$(uname -a)" in

  Linux)
    alias open="xdg-open"
    ;;

  darwin*)
    alias open="open"
    ;;

  #'Cygwin'
  CYGWIN*|MINGW32*|MSYS*|MINGW*)
    alias open="cmd /c start"
    ;;

  #'WSL2'
  WSL*|micorsoft*)
    alias open='/mnt/c/Windows/explorer.exe'
    ;;
esac

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
    if [ $# -eq 0 ]; then
        open .;
    else
        open "$@";
    fi;
}


