#!/bin/bash
# bash script to change login screen of GTK-webkit reader
img=$1

style_file=/usr/share/lightdm-webkit/themes/aqua/resources/css/style.css
sudo cp -r  ./$img /usr/share/backgrounds/current

# regex also finds "/" too
replacement="/$img"

# on line 46 
sudo sed -i -E --expression "46s#/[^a-zA-Z]/*.*jpg#/$img#" $style_file
